const fathomGoals = () => {
  if (process.env.REACT_APP_FATHOM_ENV === 'production') {
    return {
      SWAP_INTENT: 'S0KCFF7F',
      SWAP_COMPLETE: 'EGT3DZLX',
      WRAP_INTENT: 'TMDR9X4O',
      WRAP_COMPLETE: 'J4MILHXE',
      UNWRAP_INTENT: '1YU6ME7D',
      UNWRAP_COMPLETE: 'QC9OMXOA',
      CANCEL_INTENT: 'GQSDISFO',
      CANCEL_COMPLETE: 'PADWRJDR',
      ACCOUNT_CONNECTED: 'K9GZPRL4'
    }
  }
  return {
    WRAP_INTENT: 'W4SHAOVD',
    WRAP_COMPLETE: 'DVENJKDG',
    UNWRAP_INTENT: 'MBJQE5VT',
    UNWRAP_COMPLETE: 'CEEDDU06',
    SWAP_INTENT: 'AQMUJISQ',
    SWAP_COMPLETE: 'G6QMR6GI',
    CANCEL_INTENT: 'GZWTXZJ6',
    CANCEL_COMPLETE: 'WL9TKL6Q',
    ACCOUNT_CONNECTED: 'O7INS7NB'
  }
}

export default fathomGoals()
