const fathomGoals = () => {
  if (process.env.REACT_APP_FATHOM_ENV === 'production' && window.location.host === 'app.mistx.io') {
    return {
      SWAP_INTENT: 'S0KCFF7F',
      SWAP_COMPLETE: 'EGT3DZLX',
      WRAP_INTENT: 'TMDR9X4O',
      WRAP_COMPLETE: 'J4MILHXE',
      UNWRAP_INTENT: '1YU6ME7D',
      UNWRAP_COMPLETE: 'QC9OMXOA',
      CANCEL_INTENT: 'GQSDISFO',
      CANCEL_COMPLETE: 'PADWRJDR',
      METAMASK_CONNECTED: 'K9GZPRL4',
      WALLET_CONNECT_CONNECTED: 'KF01BKBA',
      LEDGER_CONNECTED: 'UIFMKUPR',
      WALLET_CONNECTED: ''
    }
  }
  return {
    WRAP_INTENT: 'W4SHAOVD',
    WRAP_COMPLETE: 'DVENJKDG',
    UNWRAP_INTENT: 'MBJQE5VT',
    UNWRAP_COMPLETE: 'CEEDDU06',
    SWAP_INTENT: 'AQMUJISQ',
    SWAP_COMPLETE: 'G6QMR6GI',
    CANCEL_INTENT: 'GZWTXZJ6',
    CANCEL_COMPLETE: 'WL9TKL6Q',
    METAMASK_CONNECTED: 'O7INS7NB',
    WALLET_CONNECT_CONNECTED: 'A6ICCX3D',
    LEDGER_CONNECTED: 'NSO3AQD7',
    WALLET_CONNECTED: ''
  }
}

export default fathomGoals()
