const fathomGoals = () => {
  if (process.env.REACT_APP_FATHOM_ENV === 'production') {
    return {
      SWAP_INTENT: 'S0KCFF7F',
      SWAP_COMPLETE: 'EGT3DZLX',
      WRAP_INTENT: 'TMDR9X4O',
      WRAP_COMPLETE: 'J4MILHXE',
      UNWRAP_INTENT: '1YU6ME7D',
      UNWRAP_COMPLETE: 'QC9OMXOA',
      CANCEL_INTENT: 'GQSDISFO',
      CANCEL_COMPLETE: 'PADWRJDR',
      ACCOUNT_CONNECTED: 'K9GZPRL4'
    }
  }
  return {
    WRAP_INTENT: '6VKRIA34',
    WRAP_COMPLETE: 'TEDXDAY6',
    UNWRAP_INTENT: 'UXNPQG4C',
    UNWRAP_COMPLETE: 'SUBD6KBH',
    SWAP_INTENT: 'GIIEFO3L',
    SWAP_COMPLETE: 'AED2FILB',
    CANCEL_INTENT: 'YRZMSENQ',
    CANCEL_COMPLETE: 'AED2FILB',
    ACCOUNT_CONNECTED: 'U9IGQOT8'
  }
}

export default fathomGoals()
